Gallery submission
BCStudentSoftwareDevTeam/Ullman_Galleries pull request #14
Opened 2018-01-20 23:08 UTC by Jessonsotoventura

Finished first draft of the page, missing copy to clipboard and link functionality

2018-01-20 23:13 UTC, memo330179 requested changes
Image needs to be moved to proper place

2018-01-20 23:17 UTC, memo330179 requested changes
We don't store images in data folder. This should be in app/static/data

2018-01-20 23:17 UTC, memo330179 commented on app/controllers/gallery_submission.py
> +from app.logic.queries import GalleryQueries
Gallery Query import need to reflect page

2018-01-20 23:17 UTC, memo330179 commented on app/logic/queries/GalleryQueries.py
> +from app.models.Galleries import *
This file needs to be moved to `app/models/queries`

2018-01-22 01:56 UTC, memo330179 approved these changes

2018-01-22 01:56 UTC, memo330179 commented on scripts/ConfigureApp.py
>  #TODO:
Is this TODO: still relevant?

2018-01-22 01:56 UTC, merged

2018-01-22 01:57 UTC, Jessonsotoventura commented on scripts/ConfigureApp.py
>  #TODO:
No I'll get rid of it soon