Gallery edit page
BCStudentSoftwareDevTeam/Ullman_Galleries pull request #15
Opened 2018-01-20 23:20 UTC by Jessonsotoventura

2018-01-20 23:30 UTC, memo330179 requested changes
This looks good. Just noted some changes.

2018-01-20 23:30 UTC, memo330179 commented on app/config/secret.yaml
> +  username: agarwali
We should not be committing this file. We will add it to the `.gitignore`

2018-01-20 23:30 UTC, memo330179 commented on app/templates/snips/base.html
> +    <script src="/static/js/ext/ckeditor/ckeditor.js"></script>
This should be moved to specific template to avoid always loading

2018-01-20 23:30 UTC, memo330179 commented on app/templates/views/gallery_edit.html
> +                $('#startDate').datetimepicker();
Javascript should be moved to it's own file `app/static/js/local/filename`.

2018-01-20 23:30 UTC, memo330179 commented on app/templates/views/gallery_edit.html
> +                $('#endDate').datetimepicker();
Javascript should be moved to its own file app/static/js/local/filename.

2018-01-20 23:30 UTC, memo330179 commented on app/templates/views/gallery_edit.html
> +        CKEDITOR.replace( 'editor1' );
Javascript should be moved to its own file app/static/js/local/filename.

2018-01-22 01:43 UTC, memo330179 commented
@agarwali I just realized you probably don't get notifications to this PR.

2018-01-29 13:20 UTC, memo330179 submitted a review, later dismissed
We should not bloat the repo by including dependencies. We should either use NPM, wget, or some other method of installation during the application setup.

2018-01-29 20:44 UTC, Jessonsotoventura commented
I think @agarwali has a good reason for adding in the dependency. I believe that if we stray from the default ckeditor build it makes it hard to include using NPM or wget, since the config files change. In this case I think we may end up changing the standard button config, but we will certainly change the theme to bootstrap. @memo330179 at least using the a custom theme requires a custom build

2018-01-29 20:53 UTC, Jessonsotoventura commented on app/logic/validation.py
> +    print ("Query working", user)
Can we remove this print if the function works? 
I think it will get bothersome to have so many prints in the console.

2018-01-29 20:53 UTC, Jessonsotoventura commented on app/models/queries/GalleryQueries.py
> +
Thanks for creating and commenting on these, they look good 👍

2018-01-29 20:53 UTC, Jessonsotoventura commented on app/static/js/local/gallery_edit.js
> +    customConfig: '/static/js/ckeditor/custom_config.js'
Going back to @memo330179's comment could we use a base install say from a CDN and use this to load the custom parts  like the bootstrap theme?

2018-01-31 04:18 UTC, merged